virtual/blas/blas-2.1-r3.ebuild
=> Upping eigen dependency for virtual/blas

licenses/FSL, licenses/newmat
Needed for [the FSL pull request](https://github.com/gentoo-science/sci/pull/118), see discussion starting [here](https://github.com/gentoo-science/sci/pull/118#issuecomment-79497202).
=> new licences (needed for FSL package)

eclass/emboss-r1.eclass, sci-biology/embassy-cbstools/embassy-cbstools-1.0.0.650.ebuild, sci-biology/embassy-clustalomega/embassy-clustalomega-1.1.0.ebuild, sci-biology/embassy-domainatrix/embassy-domainatrix-0.1.650.ebuild, sci-biology/embassy-domalign/embassy-domalign-0.1.650.ebuild, sci-biology/embassy-domsearch/embassy-domsearch-0.1.650.ebuild, sci-biology/embassy-emnu/embassy-emnu-1.05.650.ebuild, sci-biology/embassy-esim4/embassy-esim4-1.0.0.650.ebuild, sci-biology/embassy-hmmer/embassy-hmmer-2.3.2.650.ebuild, sci-biology/embassy-iprscan/embassy-iprscan-4.3.1.650.ebuild, sci-biology/embassy-meme/embassy-meme-4.7.650.ebuild, sci-biology/embassy-mse/embassy-mse-3.0.0.650.ebuild, sci-biology/embassy-phylipnew/embassy-phylipnew-3.69.650.ebuild, sci-biology/embassy-signature/embassy-signature-0.1.650.ebuild, sci-biology/embassy-structure/embassy-structure-0.1.650.ebuild, sci-biology/embassy-topo/embassy-topo-2.0.650.ebuild, sci-biology/embassy-vienna/embassy-vienna-1.7.2.650.ebuild, sci-biology/emboss/emboss-6.6.0.ebuild
emboss-r1.eclass has been modified to address criticisms made in
http://article.gmane.org/gmane.linux.gentoo.devel/94991
=> Updated emboss-r1.eclass and all embassy/emboss packages to confirm to QA

sci-mathematics/netgen/netgen-5.0.0.ebuild
Added dependency with metis and metis include directory
=> add metis dependency #408

dev-java/jrosetta/jrosetta-1.0.4.ebuild
solves issue https://github.com/gentoo-science/sci/issues/412
=> dev-java/jrosetta: switching to fedora mirror because upstream server unavailable

sci-libs/pydicom/ChangeLog, sci-libs/pydicom/pydicom-0.9.8.ebuild, sci-libs/pydicom/pydicom-9999.ebuild
new live ebuild supporting more python versions
=> Pydicom live ebuild

sci-libs/vxl/ChangeLog, sci-libs/vxl/metadata.xml, sci-libs/vxl/vxl-9999.ebuild
Dependency for [Freesurfer](https://github.com/gentoo-science/sci/issues/401).
=> New pull request for sci-libs/vxl

dev-tex/pythontex/ChangeLog, dev-tex/pythontex/pythontex-0.14-r1.ebuild, dev-tex/pythontex/pythontex-9999.ebuild
See https://github.com/gentoo-science/sci/issues/441#issuecomment-114127425
=> pruned deps for dev-tex/pythontex

sci-biology/ncbi-tools++/ChangeLog, sci-biology/ncbi-tools++/ncbi-tools++-12.0.0.ebuild
fixes https://github.com/gentoo-science/sci/issues/445
=> sci-biology/ncbi-tools++ added dep needed at build-time

sci-libs/nipype/ChangeLog, sci-libs/nipype/nipype-9999.ebuild
Package-Manager: portage-2.2.20
=> need sqlite3 module for sci-libs/nipype

sci-biology/ants/ChangeLog, sci-biology/ants/ants-9999.ebuild, sci-biology/ants/metadata.xml
replacement for https://github.com/gentoo-science/sci/pull/435 which got all messed up on the git side of things...
=> New ANTS pull request

dev-python/ipyparallel/ChangeLog, dev-python/ipyparallel/ipyparallel-9999.ebuild, dev-python/ipywidgets/ChangeLog, dev-python/ipywidgets/ipywidgets-9999.ebuild, dev-python/jupyter_client/ChangeLog, dev-python/jupyter_client/jupyter_client-9999.ebuild, dev-python/jupyter_console/ChangeLog, dev-python/jupyter_console/jupyter_console-9999.ebuild, dev-python/jupyter_core/ChangeLog, dev-python/jupyter_core/jupyter_core-9999.ebuild, dev-python/nbconvert/ChangeLog, dev-python/nbconvert/files/nbconvert-4.0.0-pandoc-highlighting.patch, dev-python/nbconvert/nbconvert-9999.ebuild, dev-python/nbformat/ChangeLog, dev-python/nbformat/nbformat-9999.ebuild, dev-python/notebook/ChangeLog, dev-python/notebook/notebook-9999.ebuild, dev-python/qtconsole/ChangeLog, dev-python/qtconsole/qtconsole-9999.ebuild, dev-python/traitlets/ChangeLog, dev-python/traitlets/traitlets-9999.ebuild
* Fix some minor dependencies issues with packages and running tests
* Add doc use flags to all Jupyter/IPython packages with sphinx docs
=> Various Jupyter doc and deps fixes

sci-libs/rdkit/ChangeLog, sci-libs/rdkit/rdkit-2015.03.1.ebuild, sci-libs/rdkit/rdkit-9999.ebuild
Package-Manager: portage-2.2.20-prefix
=> sci-libs/rdkit: simplify USE checks

www-client/casperjs/ChangeLog, www-client/casperjs/casperjs-1.1_beta3.ebuild
=> www-client/casjerjs: Fix installation of casperjs executable

sci-biology/pysurfer/ChangeLog, sci-biology/pysurfer/files/0.6-headless_build.patch
=> sci-biology/pysurfer: updated patch

sci-biology/pysurfer/ChangeLog, sci-biology/pysurfer/files/0.6-headless_build.patch
Finally fixed my patch issue. One hunk got deprecated. Solves #514
=> sci-biology/pysurfer: removed deprecated patch section

sci-biology/fsl/ChangeLog, sci-biology/fsl/fsl-5.0.8.ebuild
=> sci-biology/fsl: new sources location (upstream removes old sources)

sci-libs/nipype/ChangeLog, sci-libs/nipype/nipype-9999.ebuild
linked dependency discussed in #530
=> sci-libs/nipype: added dep on future

sci-biology/fsl/ChangeLog, sci-biology/fsl/fsl-5.0.8.ebuild
=> sci-biology/fsl: added info about updating environment

sci-biology/nistats/ChangeLog, sci-biology/nistats/metadata.xml, sci-biology/nistats/nistats-9999.ebuild
New package (will possibly replace sci-biology/nipy).
=> sci-biology/nistats: added new package

sci-biology/spm/spm-12_p6470.ebuild
Corrected spm-spm12_p6470 source/install directories
=> SPM bugfix

sci-biology/mricron/mricron-9999.ebuild
Package-Manager: portage-2.2.27
=> sci-biology/mricron: added required eclass, updated copyright and EAPI

sci-biology/fsl/fsl-5.0.8.ebuild
=> cluster to fsl_cluster rename

sci-biology/ants/ants-9999.ebuild, sci-biology/ants/files/99ants
ANTs comes with a umber of scripts which call its core functions - and which are what many researchers preferentially use.
=> sci-biology/ants: install scripts

sci-libs/nipype/nipype-0.12.0.ebuild, sci-libs/nipype/nipype-0.12.1.ebuild, sci-libs/nipype/nipype-9999.ebuild
=> sci-libs/nipype: added dep

sci-libs/nipype/nipype-0.11.0.ebuild, sci-libs/nipype/nipype-0.12.0.ebuild, sci-libs/nipype/nipype-0.12.1.ebuild, sci-libs/nipype/nipype-9999.ebuild
Nipype requires threads → https://github.com/nipy/nipype/blob/master/nipype/interfaces/io.py#L149.
=> sci-libs/nipype: added threads REQ_USE

sci-biology/psychopy/psychopy-1.78.00.ebuild, sci-biology/psychopy/psychopy-1.83.03.ebuild, sci-biology/psychopy/psychopy-1.84.0.ebuild, sci-biology/psychopy/psychopy-9999.ebuild
More deps for psychopy (opencv, moviepy).
Added threads requirements.
=> sci-biology/psychopy: added deps for video rendering

dev-python/pydotplus/pydotplus-2.0.2.ebuild
=> dev-python/pydotplus: updted EAPI and Python compatibility

dev-python/prov/prov-1.4.0.ebuild
=> dev-python/prov: updated python compatibility and fixed test phase

sci-libs/nipy/nipy-0.4.0.ebuild, sci-libs/nipy/nipy-9999.ebuild
=> sci-libs/nipy: updated python compatibility and EAPI

sci-biology/nireg/metadata.xml, sci-biology/nireg/nireg-9999.ebuild
=> sci-biology/nireg:new ebuild

sci-biology/nistats/nistats-9999.ebuild
Package-Manager: portage-2.3.1
=> sci-biology/nistats: added new dep, updated EAPI and python compatibility

sci-libs/nibabel/nibabel-1.3.0.ebuild, sci-libs/nibabel/nibabel-2.0.1.ebuild, sci-libs/nibabel/nibabel-2.1.0.ebuild, sci-libs/nibabel/nibabel-9999.ebuild
Package-Manager: portage-2.3.1
=> sci-libs/nibabel: updted test depenencies, python compatibility, EAPI

sci-biology/nilearn/nilearn-0.1.4.1.ebuild, sci-biology/nilearn/nilearn-0.2.4.ebuild, sci-biology/nilearn/nilearn-0.2.5.ebuild, sci-biology/nilearn/nilearn-0.2.6.ebuild, sci-biology/nilearn/nilearn-9999.ebuild
Fixes https://github.com/nilearn/nilearn/issues/1287
=> sci-biology/nilearn: fixed gtk testing error

sci-libs/nipype/nipype-0.11.0.ebuild, sci-libs/nipype/nipype-0.12.0.ebuild, sci-libs/nipype/nipype-0.12.1.ebuild
Package-Manager: portage-2.3.2
=> sci-libs/nipype: added missing dep

sci-libs/nipype/nipype-9999.ebuild
Sorry @jlec , the brackets weren't commented in the previous PR.
=> sci-libs/nipype: fixed sed syntax

sci-mathematics/giac/giac-1.1.0.ebuild
=> sci-mathematics/giac: bug-fix for bugzilla bug 598008

dev-python/matplotlib-venn/matplotlib-venn-0.11.ebuild
and bumped EAPI and python compatibility.
=> dev-python/matplotlib-venn: enabled test phase

sci-mathematics/gismo/files/2017.03.21/gsAxel-CMakeLists.txt.patch, sci-mathematics/gismo/gismo-2017.03.21.ebuild, sci-mathematics/gismo/metadata.xml
sci-mathematics/gismo: added use-flag for building a sci-mathematics/axel plugin
Package-manager: portage-2.3.3 repoman-2.3.1
=> sci-mathematics/gismo: added use-flag for building a sci-mathematics/axel plugin

sci-visualization/surf-ice/surf-ice-9999.ebuild
Package-Manager: Portage-2.3.5, Repoman-2.3.2
=> sci-visualization/surf-ice: further corrected library installation

sci-visualization/mricrogl/mricrogl-9999.ebuild
Package-Manager: Portage-2.3.5, Repoman-2.3.2
=> sci-visualization/mricrogl: corrected library installation

sci-libs/nipype/nipype-9999.ebuild
Package-Manager: Portage-2.3.6, Repoman-2.3.3
=> sci-libs/nipype: added dependencies

dev-python/bokeh/bokeh-2.4.2.ebuild, dev-python/kmapper/kmapper-2.0.1-r1.ebuild, dev-python/snakemake/snakemake-7.32.4.ebuild, dev-python/snakemake/snakemake-8.16.0.ebuild, sci-biology/multiqc/multiqc-1.23.ebuild, sci-libs/daal4py/daal4py-2023.0.2.ebuild, sci-visualization/fsleyes/fsleyes-1.5.0.ebuild
See-also: https://github.com/gentoo/gentoo/commit/832063fcffe02eb04f68486146ceb7b214197961
=> */*: Rename dev-python/{jinja → jinja2}
