sci-libs/arrayfire/arrayfire-9999.ebuild
Sorry for the circumstances, but I forget to adjust DEPEND after some experiments with unzip.
=> sci-libs/arrayfire: Fix DEPEND and replace unpacker by unpack

sci-biology/quicktree/quicktree-1.1-r1.ebuild
Also the ChangeLog states it was already bumped, is was still EAPI=2.
>  16 Jun 2013; Justin Lecher <jlec@gentoo.org> quicktree-1.1-r1.ebuild,
>  metadata.xml:
>  Bump to EAPI=5 and fix license
=> sci-biology/quicktree: Really move to EAPI=5

dev-libs/libconfig/ChangeLog, dev-libs/libconfig/libconfig-9999.ebuild, dev-libs/libconfig/metadata.xml
The current version of libconfig in the git repository contain some minor fixes. E.g. the gentoo specific patches are not needed any longer.
=> dev-libs/libconfig-9999: Add ebuild to overlay

sci-libs/arrayfire/ChangeLog, sci-libs/arrayfire/arrayfire-0.9999.ebuild, sci-libs/arrayfire/arrayfire-9999.ebuild
The [default branch](https://github.com/arrayfire/arrayfire/branches) of the arrayfire repository is devel. I doubt it is a good idea to pull this, so setting EGIT_BRANCH to pull the master.
Further, the git url was missing.
=> sci-libs/arrayfire: Pull master branch; Add git url; Remove keywords

sci-libs/arrayfire/arrayfire-9999.ebuild
Unfortunately, I didn't have tested well enough. Installation of bin2cpp executable is now fixed.
=> sci-libs/arrayfire: Fix dobin of bin2cpp

dev-util/nvidia-cuda-sdk/nvidia-cuda-sdk-7.0.18.ebuild
Fix header and copyright, but much more imported fixed the KEYWORDS. This removes the QA errors.
=> Fix KEYWORDS in nvidia-cuda-sdk ebuild

media-gfx/librecad/librecad-2.0.7.ebuild, media-gfx/librecad/metadata.xml
- Fix the ${S} variable, build fails with wrong non-existent source directory
- Some improvements, and add tools USE flag present in 2.0.6 from the main portage tree.
=> Fix ebuild for librecad 2.0.7

sci-libs/calculix-ccx/calculix-ccx-2.8_p2.ebuild
thanks to jlec for notice
A missing mistake in addition to #422
=> sci-libs/calculix-ccx: inherit fortran-2 as well

dev-python/pyfftw/ChangeLog, dev-python/pyfftw/pyfftw-9999.ebuild
I tried to implement the python_test() phase for pyfftw, unfortunately all tests fail with
`ImportError: No module named 'pyfftw.pyfftw'`
I tested
```bash
cd "${TEST_DIR}" || die
```
and
```bash
cd "${TEST_DIR}"/lib || die
```
as described in the [wiki](https://wiki.gentoo.org/wiki/Project:Python/distutils-r1#distutils_install_for_testing), but had no luck. Maybe somebody sees my mistake and can help.
In this ebuild, the package is named `pyfftw` while upstream names it `pyFFTW`. Anyway, renaming the ebuilds didn't helped. Thus, this shouldn't be a naming problem.
=> dev-python/pyfftw: Implement python_test()

sci-libs/pagmo/ChangeLog, sci-libs/pagmo/pagmo-9999.ebuild
The PaGMO library moved from sourceforge to GitHub, as described in http://sourceforge.net/projects/pagmo/.
=> Updated pagmo URIs.

dev-java/jlatexmath-fop/ChangeLog, dev-java/jlatexmath-fop/jlatexmath-fop-1.0.3.ebuild, sci-mathematics/scilab/ChangeLog, sci-mathematics/scilab/files/scilab-5.5.2-batik-1.8.patch, sci-mathematics/scilab/files/scilab-5.5.2-fop-2.0.patch, sci-mathematics/scilab/files/scilab-5.5.2-xmlgraphics-common-2.0.patch, sci-mathematics/scilab/scilab-5.5.2.ebuild
Scilab 5.5.2's Java code doesn't compile unmodified against batik-1.8, fop-2.0, and xmlgraphics-common-2.0, so I've written some patches to get it building again.  I'm not familiar with the Scilab internals or the libraries above, but the fixes seemed simple enough.  I'll take care of sending them upstream.
Also dev-java/jlatexmath-fop-1.0.3 specified an incorrect jar dep, preventing it from building.
=> Fix Scilab and jlatexmath-fop to build with new versions of dependencies

sci-libs/nipype/ChangeLog, sci-libs/nipype/nipype-9999.ebuild
USE flag specification in accordance with the pyton-r1 eclass. https://github.com/gentoo-science/sci/pull/448#discussion_r35495082
=> fixed USE flag requirement

media-gfx/librecad/librecad-2.0.8.ebuild
Hi, this adds a missing dependency on dev-qt/qtprintsupport when building with the qt5 USE flag.
=> media-gfx/librecad: add a missing dependency with USE="qt5"

sci-mathematics/scilab/ChangeLog, sci-mathematics/scilab/scilab-5.5.2-r1.ebuild
Without the MPROTECT PaX mark, Scilab gets killed during the build when it tries to load Java to build documentation:
-- Building documentation (en_US) --
LANG=C LC_ALL=en_US.UTF-8 SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 ./bin/scilab-adv-cli -noatomsautoload -nb -l en_US -nouserstartup -e "try xmltojar([],[],'en_US');catch disp(lasterror()); exit(-1);end;exit(0);"
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000003461105f000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
Makefile:2142: recipe for target 'doc' failed
make: *** [doc] Error 1
* ERROR: sci-mathematics/scilab-5.5.2::science failed (compile phase):
*   emake failed
=> sci-mathematics/scilab: Add PaX mark required for Java binaries on hardened.

dev-python/symengine/ChangeLog, dev-python/symengine/metadata.xml, dev-python/symengine/symengine-9999.ebuild, sci-libs/symengine/symengine-9999.ebuild
Upstream split `symengine` into the [C++ library](https://github.com/symengine/symengine), and [external python bindings](https://github.com/symengine/symengine.py).
This ebuild uses a separate package for python support in the development version, that is now compatible with more than one python installation.
(Note: Is is preferable to include the python binding sources in the original ebuild and have a `USE` flag handle its installation instead of a separate package?)
=> sci-libs/symengine: split out bindings to dev-python/symengine

sci-physics/root/ChangeLog, sci-physics/root/files/root-6.06.00-nobyte-compile.patch, sci-physics/root/root-9999.ebuild
New nobyte-compile patch, paths for gl2ps changed,
DOCS files changed.
Package-Manager: portage-2.2.24
The `DOCS=($(find README/* -maxdepth 1 -type f))` is necessary since they have now a folder "README" in their repo which breaks with EAPI=4 by default, that folder contains the usual files like INSTALL etc.
=> sci-physics/root: Update to upstream changes.

sci-libs/rdkit/rdkit-2015.03.1.ebuild, sci-libs/rdkit/rdkit-9999.ebuild
rdkit should requires that boost is installed with python support.
=> fix dependency on boost[python]

eclass/alternatives-2.eclass
eclass/alternatives-2.eclass: support Prefix. Fixes #453.
Use ALTERNATIVESDIR_ROOT for ${ED}.
app-admin/eselect-* has been renamed to app-select/eselect-*.
recover colon-separated pairs for ALTERNATIVES_CREATED.
files/eselect-1.4.5-alternatives.patch: refresh patch for Prefix.
=> eclass/alternatives-2.eclass: support Prefix.

sci-libs/clfft/clfft-2.8-r1.ebuild
Do not use boost static libs.
This could be set as a use flag to let the user choose (not the case here).
Tested with `client` USE flag set. I did not test the other flags.
=> Created new revision to fix client not being built.

sci-chemistry/wxmacmolplt/files/wxmacmolplt-7.6.1-pkg_config.patch, sci-chemistry/wxmacmolplt/wxmacmolplt-7.6.1.ebuild
There already were checks for ming and glew library presence, but they didn't use pkg-config. Now it uses PKG_CHECK_MODULES to get link flags for all three libraries - glu, glew and ming.
=> sci-chemistry/wxmacmolplt: Use pkg-config to get link flags

sci-biology/ugene/ugene-1.20.0.ebuild
workflow_designer plugin needs QtScriptTools, so make this flag
mandatory.  Tested with qtscript-5.5.1.
=> ugene-1.20.0 needs qtscript[scripttools]

virtual/blas/blas-2.1-r5.ebuild
My systems have sci-libs/atlas, and this bug caused portage to pull in blas-reference instead.
Package-Manager: portage-2.2.26
Signed-off-by: Marc Joliet <marcec@gmx.de>
=> virtual/blas-2.1-r5: add missing "||"

dev-python/pydotplus/pydotplus-2.0.2.ebuild
Repairs pydotplus (it currently does not build due to unnecessary and incorrect source dir specificaion).
=> dev-python/pydotplus: deleted erroneous source dir

sci-physics/genfit/genfit-9999.ebuild
Upstream moved current development to github
in the last weeks.
=> sci-physics/genfit: Change live-ebuild to github.

sci-visualization/mricrogl/mricrogl-1.0.20151111.ebuild
Especially relevant since we currently have no working MRIcroGL ebuild, as per issu #618
=> sci-visualization/mricrogl: new versioned ebuild

dev-python/pydotplus/pydotplus-2.0.2.ebuild
We need to let portage know that this package works on 3.4 so that 3.4 compatible ebuilds that depend on it are considered valid (e.g. #617 ).
=> dev-python/pydotplus: added 3.4 compatibility

sci-physics/root/root-9999.ebuild
Needed at runtime of the ROOT interpreter when JITting code,
thus also necessary to build examples (and the hsimple-target).
Further details upstream: https://sft.its.cern.ch/jira/browse/ROOT-8146
Since write-access needs to actually work, addpredict is insufficient.
Writing to /dev/random should not be a security concern
(entroy is unchanged).
=> sci-physics/root-9999: current master needs write access to /dev/random

eclass/mpi.eclass, sys-cluster/mpich/mpich-3.2-r2.ebuild, sys-cluster/openmpi/openmpi-1.10.3-r2.ebuild
See [bug #519700](https://bugs.gentoo.org/show_bug.cgi?id=519700) for details
=> Add support for multilib mpi to mpi.eclass

sci-biology/abyss/abyss-1.9.0.ebuild, sci-biology/abyss/files/abyss-1.9.0-gcc-6.patch
Build failed as:
```
In file included from AssemblyAlgorithms.cpp:4:0:
../DataLayer/FastaReader.h: In member function ‘FastaReader::operator void*() const’:
../DataLayer/FastaReader.h:49:35: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘void*’ ...
operator void*() const { return m_in; }
^~~~
```
In the following source:
```c++
static bool existFile(const char* f)
{
ifstream file(f);
return file;
}
```
c++98 provides file->operator void*()
c++11 provides file->explicit operator bool()
Hence the failure on c++11.
The change adds explicit casts around istream.
Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/594254
=> sci-biology/abyss: tweak for gcc-6, bug #594254

sci-libs/nipype/nipype-0.12.0.ebuild, sci-libs/nipype/nipype-0.12.1.ebuild, sci-libs/nipype/nipype-9999.ebuild
Currently nipype-9999 (and likely future releases) won't build because setup.py requires configparser (independently of the python version for which nipype is being installed). 
As configparser is only a python-2* backport of built-in python-3* functionality, it isn't marked python-3* compatible in Portage, so it can't be fetched for python-3* installs.
=> sci-libs/nipype: setup_requires patch for python3 and configparser

sci-libs/nipype/nipype-9999.ebuild
Package-Manager: Portage-2.3.3, Repoman-2.3.1
=> sci-libs/nipype: missing dependency

eclass/numeric-int64-multibuild.eclass, virtual/blacs/blacs-1.1-r1.ebuild, virtual/blas/blas-2.1-r5.ebuild, virtual/blas/blas-3.6-r100.ebuild, virtual/blas/blas-3.7-r100.ebuild, virtual/cblas/cblas-2.0-r4.ebuild, virtual/cblas/cblas-3.6-r100.ebuild, virtual/cblas/cblas-3.7-r100.ebuild, virtual/lapack/lapack-3.6-r100.ebuild, virtual/lapack/lapack-3.7-r100.ebuild, virtual/lapacke/lapacke-3.6.ebuild, virtual/scalapack/scalapack-2.0.2.ebuild
The use of `MULTILIB_COMPAT=( abi_x86_{32,64} )` throughout the blas infrastructure in the overlay prevent any blas/lapack to be used on arch other than x86/amd64. This is perfectly justified for intel mkl and related eclass but not for something like lapack-reference. As per the `multilib-build` man page:
> Note that setting this variable effectively disables support for all other ABIs, including other architectures. For example, specifying abi_x86_{32,64} disables support for MIPS as well.
Since this is implemented as `REQUIRED_USE` restrictions, no amount of `**` in a keyword file will help. Only hacking the eclass and virtual ebuilds will help. You cannot even test the ebuild, it goes much further than signalling no one support the ebuild on other archs.
For the record, I currently …
=> Intel liberation

sci-biology/nilearn/nilearn-0.2.6.ebuild, sci-biology/nilearn/nilearn-9999.ebuild
Upstream imports joblib **not** from joblib, but from a scikits_learn bundled version.
We unbundle skits_learn for obvious reasons, so we also have to patch this.
It appears that this strange configuration arises from nilearn and scikits_learn sharing one developer who really wants this to be bundled (he has not explained why). We might be able to address the bundling issue for both packages if we bring this up again/with better arguments/in a different context:
* [trying to get **nilearn** to unbundle](https://github.com/nilearn/nilearn/pull/1398).
* [trying to get **scikits_learn** to unbundle](https://github.com/scikit-learn/scikit-learn/issues/8494)
=> sci-biology/nilearn: importing system joblib

sci-visualization/surf-ice/surf-ice-1.0.20170202.ebuild, sci-visualization/surf-ice/surf-ice-9999.ebuild
and corrected executable name for GNOME launcher
Package-Manager: Portage-2.3.4, Repoman-2.3.2
=> sci-visualization/surf-ice: added proper app data install paths

sci-visualization/mricrogl/mricrogl-9999.ebuild
and added dependency
Package-Manager: Portage-2.3.4, Repoman-2.3.2
=> sci-visualization/mricrogl: more appropriate application lib paths

sci-libs/nipype/nipype-9999.ebuild
upstream (as of now) still insists that pytest should be available at runtime
and explicitly checks
Package-Manager: Portage-2.3.5, Repoman-2.3.2
=> sci-libs/nipype: updted dependencies

profiles/package.mask
For some reason just use masking `sci-biology/ants[vtk]` was not enough. Now I just mask the package and it revdeps.
=> profiles: mask sci-biology/{samri,ants} depends on non-existent vtk version

sci-libs/starparse/starparse-0.9-r1.ebuild
- old upstream with no updates
- no revdeps
=> sci-libs/starparse: switch to guile eclass
